### ISSUE TITLE
How to create mask for Masked style transfer?

### ISSUE THREAD

**Issue by faizankshaikh** [titu1994/Neural-Style-Transfer#16]
What did you use to create mask? Any alternatives?

**Comment by titu1994** [comment]
@faizankshaikh I generally use Photoshop. 

Load the entire content image into a new layer. Use quick select to choose all the regions you want to preserve, alternating with SHIFT + CLICK to add a region or ALT + CLICK to remove a region. 

Then just fill the entire region with white to preserve style, or black to preserve the content instead. Then select inverse of the current selection and paint it with the other color to complete the mask.

The same steps can be applied with any software which allows selection of regions of images. I believe GIMP does this as well if you are on Linux. 

On Windows, if you don't have Photoshop, you can do the same with Paint. I prefer photoshop since it allows a good deal of control and feather selection for intricate details like hair. Another (paid) software I have used in the past is Remask from Topaz Labs. It gets the job done very quickly.

**Comment by faizankshaikh** [comment]
Great. Thanks!
