### ISSUE TITLE
(Not a issue) could Neural-Style-Transfer do as good as ostagram does?

### ISSUE THREAD

**Issue by albertyou2** [titu1994/Neural-Style-Transfer#27]
hi @titu1994 
It is a really great and convenience repo!!!
I use this project  generated a lot of good images.
Thank you !

Recently I found a software named ostagram .It can give a better result in some cases.
I think maybe Neural-Style-Transfer could do as well as ostagram.right?

My question is : is there a way to generate images as well as ostagram?For example,something like parameters adjusting,network structure modification,etc.
I also notice that ostagram can change only 2 parameters: style_scale and style weight.
I think there must be a simple way to do that.

I am new to deep learning and if my question is  stupid I apologize here.
Thank you for your great work again!

**Comment by titu1994** [comment]
@albertyou2 I've seen a lot of Ostagram.ru results and they are really impressive. They are using a newer method to acheive these results in a few seconds. This repository on the other hand uses the older method which has more fine grained control over the final result, but takes far longer.

If you are using the Script Helper, it is really easy to acheive Ostagram's result : 
- Change content layer to conv3_3 (instead of default conv5_2)
- Style weight to 300
- Number of Iterations to 25 (50 or 100 if you want more precise results)
- Image size to 512
- If you want Ostagram's color preservation then check the "Preserve Color" checkbox.

That's it. This should result in similar results in comparison to Ostagram.

Here is a comparison using the bamboo art style : 
![comparison 1](https://cloud.githubusercontent.com/assets/3048602/21214043/5897f3ee-c2be-11e6-86d7-a24e1f2aad60.jpg)

As you can see, the ostagram results are very good in comparison to this repo, and it is generated much faster. However, upon closer inspection, you can see that this repo produces slightly more detail. Also, the color isn't as dark as in Ostragram's result. That means that this repository still hasn't finished its processing. Perhaps with 100 iterations it could get even better results, at the cost of execution time.

And here is a comparison using the patterned leaf style : 
![comparison-2](https://cloud.githubusercontent.com/assets/3048602/21215366/c50973b0-c2c6-11e6-9169-190a60208e59.jpg)

As you can see, the leaves are far more detailed in this repo after 100 iterations and content layer of conv4_2 instead of conv3_3

**Comment by albertyou2** [comment]
@albertyou2 
Thank you very much for reply!
I 'll follow your instructions !
Have a nice day!
