### ISSUE TITLE
Invalid float

### ISSUE THREAD

**Issue by Ratinod** [titu1994/Neural-Style-Transfer#29]
1) Run Programm
2) Programm say "XXX not in standard format"
3) Сhange all "." to ","
4) ???
5) python say "invalid float value"
[proofpics](http://imgur.com/a/ytz1o)

Fix it please.

**Comment by titu1994** [comment]
Well that's a new bug. Must be a localisation bug ?  Are you in a country which uses ',' instead of '.' to demark decimal point ?

I'm currently under a ton of course load. If you can find a fix, please make a pull request at https://github.com/titu1994/Neural-Style-Transfer-Windows

**Comment by Ratinod** [comment]
Yes. It's localisation bug.

> "...please make a pull request..." 

I'm sorry, but I have no idea how to do it. 
But I found working (probably only for me) solution.

Need add this:
> `System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US");`

before all `Convert.ToDouble` 

"all" mean:
```
CheckTVWeignt()
CheckStyleScale()
CheckMinThreshold()
CheckContentWeignt()
```
in `MainForm.cs`

But, even after that, again, there are errors. And I don't know how to fix it, and what's the problem ...
[Here are screenshots of errors.](http://imgur.com/9IL9NhT)
Need some help. Again.

**Comment by titu1994** [comment]
That error has been corrected in an earlier commit. You can download the repo again or copy paste the most recent code to get that working. 

I'll be using your fix after testing that it doesn't break anything else in a few days.

**Comment by Ratinod** [comment]
> "...download the repo again..."

And then there was a new "bug"...  [Screenshot](http://imgur.com/XiA8u5U)
An endless stream of errors...
What's wrong now? How to fix it?
P.S. I'm tired of trying to catch each time disappearing ( in an instant) window with error.

**Comment by titu1994** [comment]
Are you using Theano in GPU mode? Because your errors suggest that you are using the CPU. This code is not meant for CPU execution, since it takes thousands of seconds per iteration on even the most powerful CPUs. 

This is an error with linking BLAS libraries on CPU mode. 

To setup Theano on GPU, use the Guide.md on the repo page. It has full instructions to setup Theano with GPU on windows. 

As a side note, in order to see the error screen properly, there is a second button called "Copy to Clipboard" which copies the arguments. 

Then travel to the place where the program is, go to the script directory, open a cmd with Shift + right click at that location and type `python network.py ` (with the space) and then paste (right click and paste, or ctrl V if on windows 10). 

Then the error screen will stay on the screen.

**Comment by Ratinod** [comment]
At last I was able to get it to work properly!
My problem was that I didn't see anywhere mention in "README.md" about "Guide.md" until you say me that. 
It turned out that it is necessary to use the Anaconda 3 (I had Anaconda 2). And instead of "Visual Studio 2015" need to use "Visual Studio 2013".
Ideally, you want someone to make a complete video tutorial that shows virtually all the steps for windows. But not me. I had enough. It should be mentioned in README.md about Guide.md . (Really. It is important information.)
[Screenshots with my test.](http://imgur.com/a/djGCi)
Now I'm going to learn how to achieve interesting results by changing settings.

### Thank you very much for your help!
And I apologize for the grammatical errors in the comments. (If they exist in the text)[because google translate]

**Comment by titu1994** [comment]
Umm, the second paragraph in the Readme.md is titled Guide with the first sentence pointing to the guide.md. Anyway. I guess I should make it more explicit.
