### ISSUE TITLE
multiple source files

### ISSUE THREAD

**Issue by lowtronik** [titu1994/Neural-Style-Transfer#32]
I believe that when trying to apply a style on multiple target files, the script tries to import them all at once in the GPU RAM.

**Comment by titu1994** [comment]
I was not able to understand what you mean. A source file is a code file (here, a python script). Each of the scripts in my repo is independent from the others, so you would only call one script.

If you meant multiple source images, then my repo doesn't support is currently. Sadly, since each image takes quite some time, I don't feel queuing multiple source images is optimal.

**Comment by lowtronik** [comment]
I'm sorry if  I was not specific. 

I tried to run    Network.py  /path/to/ *.jpg   , in order to process different pictures inside a folder (the frames of a video frame1, frame2, etc)

And i got a gpu ram error (i used a VM with 8gb )


btw, i have used various scripts that do style transfer and yours gives the best results with less hustle :+1:

**Comment by titu1994** [comment]
I see. Sadly, my script does not support *.jpg format. As I said, it works on one image at a time, so you have to specify the path to a single image. 

If you are on a linux environment, you can write a bash script to iterate through all of the image paths in a directory and call the script each time.

If you are on a windows environment, you could probably write a batch or powershell script to do the same, but it would be much more hassle than it is worth.

**Comment by lowtronik** [comment]
Yes, I will try the bash script, I already had it on the to do list.  

Btw,  I have used it with jpg files again and again. No problems at all. 

Also,  how i can modify your script , to not save each iteration,  just one file with the final iteration.
