### ISSUE TITLE
Low-res results are better than hi-res ones

### ISSUE THREAD

**Issue by rachelebellini** [titu1994/Neural-Style-Transfer#41]
Hello,

I am using your tool to change the style of a high-res image (about 1k x 1k). 
When I run it with --image_size = 400 I get very nice results, but then if I run it with --image_size = 1000 the results are not as good since they are too similar to the content image.

I tried to increase num_iter and to increase style_weight and decrese content_weight but I seem to get nothing really different. 

Do you have any suggestion about how to get in hi-res similar results to what I have in low-res?

Thank you

**Comment by titu1994** [comment]
Hmm, I think it's because the gradients for large images are scattered a lot. 

My usual advice is to split the image into segments and then run it over each segment. But then there will be discontinuity remnants in the image. 

Instead, maybe try multi scale transfer on lower res images like 256x256 and scale up to 1000? It's gonna take a lot longer though.

**Comment by rachelebellini** [comment]
Thank you Titu for your answer.

Could you explain me a bit more in detail how I could do a multi-scale transfer? I see you talk about it in "all transfer technique", but it's not clear to me what exactly you are doing. Could list the steps of your process please?

Thanks
